### PR TITLE
Feature/documentation basePath prefix fix - closes #694

### LINKED ISSUE #694: Change basePath in swagger.json to use apiBackend.frontendPrefix
The `baseUrl` setting in `swagger.json` is currently [set to the value of Meteor.apiUmbrella.basePath](https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/routes/jsonRoutes.js#L20). This will cause errors. Change the JsonRoute to use the [frontend prefix from the API Backend configuration](https://github.com/apinf/api-umbrella-dashboard/blob/develop/both/collections/backend.js#L91).

# Definition of done
* [x] [swagger.json is autogenerated from JsonRoute](https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/routes/jsonRoutes.js#L1)
* [x] in autogenerated swagger.json
  * [x] [`basePath`](https://github.com/swagger-api/swagger-spec/blob/master/examples/v2.0/json/petstore-simple.json#L16) is set to value of [`url_matches.frontend_prefix`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/both/collections/backend.js#L91)
  * [x] `basePath` value **does not include** `/api-umbrella/` prefix

### PR DESCRIPTION
**Pull request by frenchbread**

### CODE REVIEW

**Comment by frenchbread** [comment]
@brylie Please review. Related issue #694

File: server/routes/jsonRoutes.js [hunk 1]
```diff
@@ -1,24 +1,30 @@
 JsonRoutes.add("get", "api/:id/swagger.json", function (request, response, next) {
 
+  // Get current id
+  var id = request.params.id;
```
Comment (brylie) [inline server/routes/jsonRoutes.js]: What `id` is this? Please be more specific with variable names, as it improves readability. Be sure to update your comment with a more specific description.

File: server/routes/jsonRoutes.js [hunk 2]
```diff
@@ -1,24 +1,30 @@
...
+
   // Get basePath for apiUmbrella from Meteor settings file
   var apiUmbrellaBaseUrl = Meteor.settings.apiUmbrella.baseUrl;
 
-  // Remove trailing slash
-  apiUmbrellaBaseUrl = apiUmbrellaBaseUrl.replace(/\/$/, '');
-
   // Parse basePath string to URI obj
   var baseURL = new URI(apiUmbrellaBaseUrl);
```
Comment (brylie) [inline server/routes/jsonRoutes.js]: Go ahead and rename this to `baseUrl`. Good work on cleaning up this function :-)

**Comment by brylie** [comment]
This looks good. There are just a couple of minor issues relating to readability.

**Comment by frenchbread** [comment]
Added suggested changes to a working branch.

File: server/routes/jsonRoutes.js [hunk 3]
```diff
@@ -1,24 +1,30 @@
 JsonRoutes.add("get", "api/:id/swagger.json", function (request, response, next) {
 
+  // Get current apiDocument Id
+  var id = request.params.id;
```
Comment (brylie) [inline server/routes/jsonRoutes.js]: Go ahead and change the variable name to `apiDocumentId`. It is important that variable names are semantic, since they are used throughout the souce. I.e. all lines of source should be semantic as well as comments.
