### PR TITLE
Feature/api backlog fixes

### LINKED ISSUE #1446: Fix API Backlog add/edit/delete forms and deprecate the afModals
The API Backlog forms currently do not validate. The issue has been fixed in a PR, but that PR will not get merged. Use the API Backlog modal code from the 'restructure-project' branch to fix the API Backlog. Also, deprecate the afModals package.

### PR DESCRIPTION
**Pull request by nnn**
Closes #1446 
afModals wasnt removed, because we are still using it for feedback tab.
I propose to remove it in a separate PR.

@apinf/developers, please review.

### CODE REVIEW

File: backlog/collection/server/publications.js [hunk 1]
```diff
@@ -1,3 +1,5 @@
+import { ApiBacklogItems } from '/backlog/collection';
+
 Meteor.publish('apiBacklogItems', function(apiBackendId){
```
Comment (brylie) [inline backlog/collection/server/publications.js]: Add comment describing the purpose of this publication

File: apis/client/view/view.js [hunk 2]
```diff
@@ -1,4 +1,5 @@
 import { Apis } from '/apis/collection';
+import { ApiBacklogItems } from '/backlog/collection';
 
 Template.viewApiBackend.created = function () {
```
Comment (brylie) [inline apis/client/view/view.js]: While working in this file, change to the newer `onCreated(function () {})` syntax, rather than the deprecated `created = function () {}` approach.

For what it's worth, our linter will start enforcing this rule, since it is a recommendation of the Meteor core developers.

File: backlog/client/add/autoform.js [hunk 3]
```diff
@@ -18,19 +18,10 @@ AutoForm.hooks({
   }
 });
 
-AutoForm.addHooks(['apiBacklogForm'], {
+AutoForm.addHooks(['addApiBacklogItemForm'], {
   // Success message
   onSuccess: function () {
```
Comment (brylie) [inline backlog/client/add/autoform.js]: Move the `onSuccess` hook into the `AutoForm.hooks({})` configuration object above.

The `AutoForm.hooks({})` signature more closely resembles things like `Meteor.methods({})` and `Template.name.helpers({})` definition where we pass in a configuration object as the only argument.

File: backlog/client/edit/autoform.js [hunk 4]
```diff
@@ -0,0 +1,7 @@
+AutoForm.addHooks(['editBacklogItemForm'], {
```
Comment (brylie) [inline backlog/client/edit/autoform.js]: Switch to the `Autoform.hooks({});` syntax, for consistency.

File: backlog/client/add/autoform.js [hunk 5]
```diff
@@ -1,5 +1,5 @@
 AutoForm.hooks({
-  apiBacklogForm: {
+  addApiBacklogItemForm: {
     before: {
       insert: function (backlogItem) {
```
Comment (brylie) [inline backlog/client/add/autoform.js]: Use ES2015 object literal syntax here:

```js
...
  before: {
    insert () {
      ...
    }
  }
```

File: backlog/collection/schema.js [hunk 6]
```diff
@@ -0,0 +1,69 @@
+import { ApiBacklogItems } from './';
+
+ApiBacklogItems.attachSchema(new SimpleSchema({
```
Comment (brylie) [inline backlog/collection/schema.js]: For internationalization, we need to create the schema as an intermediary step. Follow the [project collection/schema guidelines](https://github.com/apinf/api-umbrella-dashboard/blob/develop/CONTRIBUTING.md#collectionschema-structure).

**Comment by nnn** [comment]
added suggested changes, please review
