### PR TITLE
Unsuccessful in editing/deleting API backend

### LINKED ISSUE #1248: Unsuccessful in editing API backend - shows "Cannot read property 'length' of null"
Unsuccessful in editing API Backend. Tried to change the port number and press "Submit" throws an error pop up as "Cannot read property 'length' of null"

# Steps to reproduce
1.Visit https://nightly.apinf.io
2.Login as API owner by clicking on 'Sign In' 
3.Go to 'Menu' and click on ' API Backend' 
4. Go to 'Manage API Backends ' 
5.Go to API Backend and click on 'Edit' 
6.Go to 'Backend Protocol' and edit protocol (eg. http / https)
7.Go to 'Servers' and edit 'Port'  - Changed from existing 80 port to 9090
8. Click on 'Submit' button

# Observed behavior
Unsuccessful in editing API Backend details - Throws an warning note as "Cannot read property 'length' of null"

image

# Expected behavior
Successful editing API backend details.

# Environment

- Web browser: Google Chrome Version  51.0.2704.103 m
- Operating system : Windows 10

### PR DESCRIPTION
**Pull request by nnn**
Closes #1248

The problem comes when you delete API(s) on one instance, it still exists on other instances. 
This fix will check if API(s) exists on APIUmbrella and if not it will remove API(s) on every instance with next sync.

thanks @frenchbread for pair-programming.

### CODE REVIEW

**Comment by nnn** [comment]
@apinf/developers, please review.

File: apis/server/methods/apiUmbrella.js [hunk 1]
```diff
@@ -1,27 +1,49 @@
...
+
+      // Get all local API Backends
+      const localApis = ApiBackends.find().fetch();
+
+      _.forEach(remoteApis, (remoteApi) => {
 
-      _.each(apiBackends, function (apiBackend) {
         // Get existing API Backend
-        var existingApiBackend = ApiBackends.findOne({'id': apiBackend.id});
+        var existingApiBackend = ApiBackends.findOne({'id': remoteApi.id});
```
Comment (frenchbread) [inline apis/server/methods/apiUmbrella.js]: - Change `var` to `const`
- Rename `existingApiBackend` to `existingRemotelyApiBackend` or smth like that

File: apis/server/methods/apiUmbrella.js [hunk 2]
```diff
@@ -1,27 +1,49 @@
...
           } catch (error) {
-            console.error("Error inserting apiBackend(" + apiBackend.id + ") : " + error);
+            console.error("Error inserting apiBackend(" + remoteApi.id + ") : " + error);
           }
         };
       });
+
+      _.forEach(localApis, (localApi) => {
+
+        const existingApiBackend = _.find(remoteApis, (remoteApi) => {
```
Comment (frenchbread) [inline apis/server/methods/apiUmbrella.js]: Rename `existingApiBackend` to `existingLocallyApiBackend`
