### PR TITLE
Bugfix/apidocs notdefined when deleting

### LINKED ISSUE #1199: ApiDocs is not defined when deleting API Backend
When we changed API documentation behavior, that has also effect on API remove functionality, where we try to remove API documentation of API to be removed.

Stacktrace:
```
I20160622-12:25:05.083(3)? Exception while invoking method 'removeApiBackend' ReferenceError: ApiDocs is not defined
I20160622-12:25:05.084(3)?     at [object Object].removeApiBackend (apis/server/methods/delete.js:9:5)
I20160622-12:25:05.085(3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
I20160622-12:25:05.085(3)?     at packages/ddp-server/livedata_server.js:711:19
I20160622-12:25:05.085(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160622-12:25:05.086(3)?     at packages/ddp-server/livedata_server.js:709:40
I20160622-12:25:05.086(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160622-12:25:05.086(3)?     at packages/ddp-server/livedata_server.js:707:46
I20160622-12:25:05.086(3)?     at tryCallTwo (/Users/jykae/.meteor/packages/promise/.0.6.7.7hrmjt++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20160622-12:25:05.086(3)?     at doResolve (/Users/jykae/.meteor/packages/promise/.0.6.7.7hrmjt++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:200:13)
I20160622-12:25:05.086(3)?     at new Promise (/Users/jykae/.meteor/packages/promise/.0.6.7.7hrmjt++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:66:3)
```

### PR DESCRIPTION
**Pull request by jykae**
Closes #1199 

## Proposed changes
- Remove unused publication for previous API docs collection
- Fix & improve removal process, use new DocumentationFiles collection

@apinf/developers please review

### CODE REVIEW

**Comment by jykae** [comment]
Note: ApiDocs collection is still used here, https://github.com/apinf/api-umbrella-dashboard/blob/develop/apis/client/api_backends/edit/form/autoform.js#L104
and here, https://github.com/apinf/api-umbrella-dashboard/blob/develop/apis/client/api_backends/import_documentation/import.js#L56

@nnn Any idea, can they be just removed or need to update to use new DocumentationFiles?

**Comment by jykae** [comment]
@nnn I made issue #1208 for above thing, let's have another PR to check those.

File: apis/server/methods/delete.js [hunk 1]
```diff
@@ -1,12 +1,28 @@
...
     ApiMetadata.remove({"apiBackendId": apiBackendId});
-    ApiDocs.remove(apiBackendId);
+    // Finally remove the API
+    ApiBackends.remove(apiBackendId);
   }
-
 });
+
+// Helper to remove API documentation file
+function removeApiDoc(apiBackendId) {
```
Comment (brylie) [inline apis/server/methods/delete.js]: This should be defined as a Meteor method, rather than a global function.

Comment (jykae) [inline apis/server/methods/delete.js]: @brylie Is it global? I thought it's scope is only this file.

Comment (brylie) [inline apis/server/methods/delete.js]: You are right, it is scoped to the file. A Meteor method would allow us to use this function in other places, and even from the client.

Comment (jykae) [inline apis/server/methods/delete.js]: @brylie Ok, I make it Meteor method.

**Comment by jykae** [comment]
@brylie @nnn changes done.
